# -*- coding: utf-8 -*-
"""Fruit Sorting Computer Vision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_IeJX59_oogGQAKwxT_aJkNsEuX9hgv

**Fruit Sorting Simulation for Apples and Oranges**
## This Python code uses the OpenCV library to simulate the sorting of apples and oranges from an image. It identifies the fruits based on their color and shape, draws bounding boxes around them, and then simulates assigning them to different bins.


The project objective is to automate the sorting and packaging of fruits based on visual quality standards. Below is an outline of the code structure and algorithm which combines computer vision using OpenCV and basic logic for robotic arm control. This example will demonstrate the key components but ensure adaptations based on your actual hardware configurations and environment settings.

Test Case
Since this code simulates a robotic system, a good test case would involve verifying that it correctly identifies and "sorts" apples in an image. Here's a breakdown of a possible test case:

1. Input:

An image containing one or more apples (like the 'apple.jpg' used in the code). You might want to create test images with:
Different numbers of apples: One apple, two apples, several apples.
Apples in different positions: Apples near the edges, apples in the center, overlapping apples.
Varying lighting conditions: Images with bright light, dim light, shadows.
Different apple varieties: Red apples, green apples (if the color range is adjusted).
2. Expected Output:

Detection: The code should correctly identify all the apples in the image by drawing bounding boxes around them.
Labels: Each bounding box should be labeled with "Apple 1", "Apple 2", etc., to distinguish individual apples.
Sorting Simulation: The simulate_robot_arm_pick_and_place function should print messages to the console indicating that it's moving to each apple's location, picking it, and placing it in "Bin 1".
3. How to Test:

Run the code with the selected test image as input.
Visually inspect the output image displayed by matplotlib.pyplot. Check that:
All apples are correctly enclosed in bounding boxes.
There are no bounding boxes around objects that are not apples (false positives).
All bounding boxes are correctly labeled.
Observe the console output to see if the robot arm simulation is working as expected. It should print messages for each apple, simulating its movement and sorting actions.
Example Test Cases:

Test Case 1: Image with a single red apple in the center. Expected: One bounding box labeled "Apple 1", and console output simulating the robot arm picking and placing it in "Bin 1".
Test Case 2: Image with three red apples in different positions. Expected: Three bounding boxes labeled "Apple 1", "Apple 2", "Apple 3", and console output simulating the sorting of each apple.
Test Case 3: Image with two red apples overlapping. Expected: Two bounding boxes (as accurately as possible), and console output simulating the sorting of each apple.
Important Considerations:

Color Range: The code's current color range is specifically tuned for red apples. If you want to test with different apple varieties (green, yellow), you'll need to adjust the HSV values in the detect_apples function.
Image Quality: The code's performance might be affected by the quality of the test images. Blurry images or images with poor lighting could lead to inaccurate detection.
Real-World Applications: Keep in mind that this is a simulation. In real-world robotic applications, you'd need to integrate the code with actual robot arm hardware and calibrate it to work in a real environment.

1. Importing Libraries
"""

import cv2   ##cv2: This is the OpenCV library, used for computer vision tasks like image processing.
import numpy as np  ##numpy: This library is used for numerical operations, especially for working with arrays.
from matplotlib import pyplot as plt ##matplotlib.pyplot: This library is used for creating visualizations, like plotting the image with the detected fruits.

"""2. Image Preprocessing

"""

##This function takes an image as input.
#It converts the image from the BGR color space (used by OpenCV) to HSV, which is often better for color-based object detection.
#It applies Gaussian blur to reduce noise and smooth the image.
#It returns the preprocessed image.##

def preprocess_image(image):
    """Convert image to HSV and apply Gaussian blur."""
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    blurred = cv2.GaussianBlur(hsv, (7, 7), 0)
    return blurred

"""3. Creating a Mask"""

#This function takes an hsv image, lower_color, and upper_color as input.
#It creates a mask by selecting pixels within the specified lower_color and upper_color range. This isolates the desired color in the image.
#Morphological operations (opening and closing) are applied to the mask to remove noise and improve the shape of the detected objects.
#It returns the mask.
def get_mask(hsv, lower_color, upper_color):
    """Create a mask for a given color range."""
    mask = cv2.inRange(hsv, lower_color, upper_color)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5,5), np.uint8))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((5,5), np.uint8))
    return mask

"""4. Detecting Fruits"""

# This function takes an image as input.
# It preprocesses the image using preprocess_image.
# It defines color ranges for apples and oranges in the colors dictionary.
# It iterates through the colors, creates a mask for each color, and finds contours (outlines) of objects in the mask.
# It filters out small contours (noise) and checks the aspect ratio of the remaining contours to identify roundish shapes (apples and oranges).
# It appends the detected fruit and its bounding box coordinates (x, y, w, h) to the results list.
# It returns the results.

def detect_fruits(image):
    """Detect apples and oranges by color and shape and classify them."""
    hsv = preprocess_image(image)

    # Define color ranges for apple and orange (in HSV)
    colors = {
        'apple': ((0, 100, 100), (10, 255, 255)),       # Red-ish
        'orange': ((10, 100, 100), (20, 255, 255)),     # Orange-ish
    }

    results = []

    for fruit, (lower, upper) in colors.items():
        lower = np.array(lower, dtype=np.uint8)
        upper = np.array(upper, dtype=np.uint8)
        mask = get_mask(hsv, lower, upper)

        # Find contours
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for cnt in contours:
            area = cv2.contourArea(cnt)
            if area > 500:  # filter small noise
                # Approximate contour to reduce number of points
                approx = cv2.approxPolyDP(cnt, 0.02*cv2.arcLength(cnt, True), True)
                x, y, w, h = cv2.boundingRect(approx)
                aspect_ratio = float(w)/h

                # Shape check: roundish for apple and orange
                if 0.75 < aspect_ratio < 1.3:
                    results.append((fruit, (x, y, w, h)))

    return results

"""5. Drawing Results"""

# This function takes an image and results as input.
# It iterates through the results and draws a green bounding box around each detected fruit using cv2.rectangle.
# It adds a text label with the fruit name above the bounding box using cv2.putText.
# It returns the image with the drawn bounding boxes and labels.
def draw_results(image, results):
    """Draw bounding boxes and labels on the image."""
    for fruit, (x, y, w, h) in results:
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(image, fruit, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)
    return image

"""6. Simulating Sorting"""

# This function takes results as input.
# It defines a sorting_bins dictionary that maps fruit names to bin numbers.
# It iterates through the results and prints a message indicating which bin each fruit would be sorted into.

def simulate_sorting(results):
    """Simulate sorting decisions based on detected fruits."""
    sorting_bins = {
        'apple': 'Bin 1',
        'orange': 'Bin 2',
    }
    for fruit, _ in results:
        print(f"Sorting {fruit} to {sorting_bins.get(fruit, 'Unknown bin')}")

"""7. Main Function"""



# This is the main function that executes when the script is run.
# It downloads an example image of an apple.
# It calls detect_fruits to detect the fruits in the image.
# It calls draw_results to draw bounding boxes and labels on the image.
# It displays the image using matplotlib.pyplot.
# It calls simulate_sorting to simulate the sorting process.
# The if __name__ == '__main__': block ensures that main() is called only when the script is executed directly, not when it's imported as a module.

def main():
    # Load example image from URL (can be replaced with user upload in Colab)
    import urllib.request
    url = 'https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg'  # example apple image
    urllib.request.urlretrieve(url, 'apple.jpg')
    image = cv2.imread('apple.jpg')

    results = detect_fruits(image)
    image_with_boxes = draw_results(image.copy(), results)

    # Show image with detections
    plt.imshow(cv2.cvtColor(image_with_boxes, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()

    # Simulate sorting
    simulate_sorting(results)

if __name__ == '__main__':
    main()

# Fruit Sorting Simulation using OpenCV in Google Colab
# This script detects and classifies fruits based on color and shape features
# and simulates sorting decisions.

import cv2
import numpy as np
from matplotlib import pyplot as plt

def preprocess_image(image):
    """Convert image to HSV and apply Gaussian blur."""
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    blurred = cv2.GaussianBlur(hsv, (7, 7), 0)
    return blurred

def get_mask(hsv, lower_color, upper_color):
    """Create a mask for a given color range."""
    mask = cv2.inRange(hsv, lower_color, upper_color)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5,5), np.uint8))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((5,5), np.uint8))
    return mask

def detect_fruits(image):
    """Detect fruits by color and shape and classify them."""
    hsv = preprocess_image(image)

    # Define color ranges for some fruits (in HSV)
    # These ranges may need tuning depending on the image
    colors = {
        'apple': ((0, 100, 100), (10, 255, 255)),       # Red-ish
        'banana': ((20, 100, 100), (30, 255, 255)),     # Yellow-ish
        'orange': ((10, 100, 100), (20, 255, 255)),     # Orange-ish
    }

    results = []

    for fruit, (lower, upper) in colors.items():
        lower = np.array(lower, dtype=np.uint8)
        upper = np.array(upper, dtype=np.uint8)
        mask = get_mask(hsv, lower, upper)

        # Find contours
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for cnt in contours:
            area = cv2.contourArea(cnt)
            if area > 500:  # filter small noise
                # Approximate contour to reduce number of points
                approx = cv2.approxPolyDP(cnt, 0.02*cv2.arcLength(cnt, True), True)
                x, y, w, h = cv2.boundingRect(approx)
                aspect_ratio = float(w)/h

                # Simple shape check: roundness for apple and orange, elongated for banana
                if fruit == 'banana' and aspect_ratio > 1.5:
                    results.append((fruit, (x, y, w, h)))
                elif fruit in ['apple', 'orange'] and 0.75 < aspect_ratio < 1.3:
                    results.append((fruit, (x, y, w, h)))

    return results

def draw_results(image, results):
    """Draw bounding boxes and labels on the image."""
    for fruit, (x, y, w, h) in results:
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(image, fruit, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)
    return image

def simulate_sorting(results):
    """Simulate sorting decisions based on detected fruits."""
    sorting_bins = {
        'apple': 'Bin 1',
        'banana': 'Bin 2',
        'orange': 'Bin 3'
    }
    for fruit, _ in results:
        print(f"Sorting {fruit} to {sorting_bins.get(fruit, 'Unknown bin')}")

def main():
    # Load example image from URL (can be replaced with user upload in Colab)
    import urllib.request
    url = 'https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg'  # example apple image
    urllib.request.urlretrieve(url, 'apple.jpg')
    image = cv2.imread('apple.jpg')

    results = detect_fruits(image)
    image_with_boxes = draw_results(image.copy(), results)

    # Show image with detections
    plt.imshow(cv2.cvtColor(image_with_boxes, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()

    # Simulate sorting
    simulate_sorting(results)

if __name__ == '__main__':
    main()

# Fruit Sorting Simulation for Orange and Banana using OpenCV in Google Colab
# This script detects and classifies oranges and bananas based on color and shape features
# and simulates sorting decisions.

import cv2
import numpy as np
from matplotlib import pyplot as plt

def preprocess_image(image):
    """Convert image to HSV and apply Gaussian blur."""
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    blurred = cv2.GaussianBlur(hsv, (7, 7), 0)
    return blurred

def get_mask(hsv, lower_color, upper_color):
    """Create a mask for a given color range."""
    mask = cv2.inRange(hsv, lower_color, upper_color)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5,5), np.uint8))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((5,5), np.uint8))
    return mask

def detect_fruits(image):
    """Detect oranges and bananas by color and shape and classify them."""
    hsv = preprocess_image(image)

    # Define color ranges for orange and banana (in HSV)
    colors = {
        'orange': ((10, 100, 100), (20, 255, 255)),     # Orange-ish
        'banana': ((20, 100, 100), (30, 255, 255)),     # Yellow-ish
    }

    results = []

    for fruit, (lower, upper) in colors.items():
        lower = np.array(lower, dtype=np.uint8)
        upper = np.array(upper, dtype=np.uint8)
        mask = get_mask(hsv, lower, upper)

        # Find contours
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for cnt in contours:
            area = cv2.contourArea(cnt)
            if area > 500:  # filter small noise
                # Approximate contour to reduce number of points
                approx = cv2.approxPolyDP(cnt, 0.02*cv2.arcLength(cnt, True), True)
                x, y, w, h = cv2.boundingRect(approx)
                aspect_ratio = float(w)/h

                # Simple shape check: elongated for banana, roundish for orange
                if fruit == 'banana' and aspect_ratio > 1.5:
                    results.append((fruit, (x, y, w, h)))
                elif fruit == 'orange' and 0.75 < aspect_ratio < 1.3:
                    results.append((fruit, (x, y, w, h)))

    return results

def draw_results(image, results):
    """Draw bounding boxes and labels on the image."""
    for fruit, (x, y, w, h) in results:
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(image, fruit, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)
    return image

def simulate_sorting(results):
    """Simulate sorting decisions based on detected fruits."""
    sorting_bins = {
        'orange': 'Bin 1',
        'banana': 'Bin 2',
    }
    for fruit, _ in results:
        print(f"Sorting {fruit} to {sorting_bins.get(fruit, 'Unknown bin')}")

def main():
    # Load example image from URL (can be replaced with user upload in Colab)
    import urllib.request
    url = 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Orange-Fruit-Pieces.jpg'  # example orange image
    urllib.request.urlretrieve(url, 'orange.jpg')
    image = cv2.imread('orange.jpg')

    results = detect_fruits(image)
    image_with_boxes = draw_results(image.copy(), results)

    # Show image with detections
    plt.imshow(cv2.cvtColor(image_with_boxes, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()

    # Simulate sorting
    simulate_sorting(results)

if __name__ == '__main__':
    main()

# Fruit Sorting Simulation for Banana using OpenCV in Google Colab
# This script detects and classifies bananas based on color and shape features
# and simulates sorting decisions.

import cv2
import numpy as np
from matplotlib import pyplot as plt

def preprocess_image(image):
    """Convert image to HSV and apply Gaussian blur."""
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    blurred = cv2.GaussianBlur(hsv, (7, 7), 0)
    return blurred

def get_mask(hsv, lower_color, upper_color):
    """Create a mask for a given color range."""
    mask = cv2.inRange(hsv, lower_color, upper_color)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5,5), np.uint8))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((5,5), np.uint8))
    return mask

def detect_bananas(image):
    """Detect bananas by color and shape and classify them."""
    hsv = preprocess_image(image)

    # Define color range for banana (in HSV)
    colors = {
        'banana': ((20, 100, 100), (30, 255, 255)),     # Yellow-ish
    }

    results = []

    for fruit, (lower, upper) in colors.items():
        lower = np.array(lower, dtype=np.uint8)
        upper = np.array(upper, dtype=np.uint8)
        mask = get_mask(hsv, lower, upper)

        # Find contours
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for cnt in contours:
            area = cv2.contourArea(cnt)
            if area > 500:  # filter small noise
                # Approximate contour to reduce number of points
                approx = cv2.approxPolyDP(cnt, 0.02*cv2.arcLength(cnt, True), True)
                x, y, w, h = cv2.boundingRect(approx)
                aspect_ratio = float(w)/h

                # Simple shape check: elongated for banana
                if aspect_ratio > 1.5:
                    results.append((fruit, (x, y, w, h)))

    return results

def draw_results(image, results):
    """Draw bounding boxes and labels on the image."""
    for fruit, (x, y, w, h) in results:
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(image, fruit, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)
    return image

def simulate_sorting(results):
    """Simulate sorting decisions based on detected bananas."""
    sorting_bins = {
        'banana': 'Bin 1',
    }
    for fruit, _ in results:
        print(f"Sorting {fruit} to {sorting_bins.get(fruit, 'Unknown bin')}")

def main():
    # Load example image from URL (can be replaced with user upload in Colab)
    import urllib.request
    url = 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg'  # example banana image
    urllib.request.urlretrieve(url, 'banana.jpg')
    image = cv2.imread('banana.jpg')

    results = detect_bananas(image)
    image_with_boxes = draw_results(image.copy(), results)

    # Show image with detections
    plt.imshow(cv2.cvtColor(image_with_boxes, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()

    # Simulate sorting
    simulate_sorting(results)

if __name__ == '__main__':
    main()

# Fruit Sorting Simulation for Apple and Orange using OpenCV in Google Colab
# This script detects and classifies apples and oranges based on color and shape features
# and simulates sorting decisions.

import cv2
import numpy as np
from matplotlib import pyplot as plt

def preprocess_image(image):
    """Convert image to HSV and apply Gaussian blur."""
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    blurred = cv2.GaussianBlur(hsv, (7, 7), 0)
    return blurred

def get_mask(hsv, lower_color, upper_color):
    """Create a mask for a given color range."""
    mask = cv2.inRange(hsv, lower_color, upper_color)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5,5), np.uint8))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((5,5), np.uint8))
    return mask

def detect_fruits(image):
    """Detect apples and oranges by color and shape and classify them."""
    hsv = preprocess_image(image)

    # Define color ranges for apple and orange (in HSV)
    colors = {
        'apple': ((0, 100, 100), (10, 255, 255)),       # Red-ish
        'orange': ((10, 100, 100), (20, 255, 255)),     # Orange-ish
    }

    results = []

    for fruit, (lower, upper) in colors.items():
        lower = np.array(lower, dtype=np.uint8)
        upper = np.array(upper, dtype=np.uint8)
        mask = get_mask(hsv, lower, upper)

        # Find contours
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for cnt in contours:
            area = cv2.contourArea(cnt)
            if area > 500:  # filter small noise
                # Approximate contour to reduce number of points
                approx = cv2.approxPolyDP(cnt, 0.02*cv2.arcLength(cnt, True), True)
                x, y, w, h = cv2.boundingRect(approx)
                aspect_ratio = float(w)/h

                # Shape check: roundish for apple and orange
                if 0.75 < aspect_ratio < 1.3:
                    results.append((fruit, (x, y, w, h)))

    return results

def draw_results(image, results):
    """Draw bounding boxes and labels on the image."""
    for fruit, (x, y, w, h) in results:
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(image, fruit, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)
    return image

def simulate_sorting(results):
    """Simulate sorting decisions based on detected fruits."""
    sorting_bins = {
        'apple': 'Bin 1',
        'orange': 'Bin 2',
    }
    for fruit, _ in results:
        print(f"Sorting {fruit} to {sorting_bins.get(fruit, 'Unknown bin')}")

def main():
    # Load example image from URL (can be replaced with user upload in Colab)
    import urllib.request
    url = 'https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg'  # example apple image
    urllib.request.urlretrieve(url, 'apple.jpg')
    image = cv2.imread('apple.jpg')

    results = detect_fruits(image)
    image_with_boxes = draw_results(image.copy(), results)

    # Show image with detections
    plt.imshow(cv2.cvtColor(image_with_boxes, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()

    # Simulate sorting
    simulate_sorting(results)

if __name__ == '__main__':
    main()

# Fruit Sorting Robot Arm Simulation using OpenCV in Python
# This script detects apples and simulates a robot arm "hand" picking and sorting the fruit.
# The robot arm control is simulated in code with print statements and simple logic.

import cv2
import numpy as np
from matplotlib import pyplot as plt
import time

def preprocess_image(image):
    """Convert image to HSV and apply Gaussian blur."""
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    blurred = cv2.GaussianBlur(hsv, (7, 7), 0)
    return blurred

def get_mask(hsv, lower_color, upper_color):
    """Create a mask for a given color range."""
    mask = cv2.inRange(hsv, lower_color, upper_color)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5,5), np.uint8))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((5,5), np.uint8))
    return mask

def detect_apples(image):
    """Detect apples by color and shape and classify them."""
    hsv = preprocess_image(image)

    # Define color range for apple (in HSV)
    lower = np.array((0, 100, 100), dtype=np.uint8)       # Red-ish lower bound
    upper = np.array((10, 255, 255), dtype=np.uint8)      # Red-ish upper bound

    mask = get_mask(hsv, lower, upper)

    # Find contours
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    results = []

    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area > 500:  # filter small noise
            approx = cv2.approxPolyDP(cnt, 0.02*cv2.arcLength(cnt, True), True)
            x, y, w, h = cv2.boundingRect(approx)
            aspect_ratio = float(w)/h
            if 0.75 < aspect_ratio < 1.3:
                results.append((x, y, w, h))

    return results

def draw_results(image, apples):
    """Draw bounding boxes and labels on the image."""
    for i, (x, y, w, h) in enumerate(apples):
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(image, f"Apple {i+1}", (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)
    return image

def simulate_robot_arm_pick_and_place(apples):
    """Simulate robot arm picking and placing apples."""
    for i, (x, y, w, h) in enumerate(apples):
        print(f"Robot arm moving to Apple {i+1} at position ({x}, {y})")
        time.sleep(1)  # simulate time to move
        print(f"Robot arm picking Apple {i+1}")
        time.sleep(1)  # simulate picking time
        print(f"Robot arm placing Apple {i+1} into Bin 1")
        time.sleep(1)  # simulate placing time
    print("All apples sorted.")

def main():
    # Load example image from URL (can be replaced with user upload in Colab)
    import urllib.request
    url = 'https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg'  # example apple image
    urllib.request.urlretrieve(url, 'apple.jpg')
    image = cv2.imread('apple.jpg')

    apples = detect_apples(image)
    image_with_boxes = draw_results(image.copy(), apples)

    # Show image with detections
    plt.imshow(cv2.cvtColor(image_with_boxes, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()

    # Simulate robot arm picking and placing apples
    simulate_robot_arm_pick_and_place(apples)

if __name__ == '__main__':
    main()

"""Conclusion
In essence, this code uses computer vision techniques to identify apples in an image and then simulates how a robot arm could be used to pick and sort them. It's a foundation for building more complex robotic systems that can automate tasks like fruit sorting in the real world. I hope this makes it clear. Let me know if you have any other questions!
"""

# Enable GPU
!nvidia-smi

# Install necessary packages
!pip install -q tensorflow opencv-python matplotlib

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

# Set your dataset path
dataset_path = '/content/drive/MyDrive/archive (9)'

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Image generators
img_size = 100
batch_size = 32

train_datagen = ImageDataGenerator(
    rescale=1./255, validation_split=0.2,
    rotation_range=20, zoom_range=0.2, shear_range=0.2, horizontal_flip=True)

train_gen = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='categorical',
    subset='training'
)

val_gen = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation'
)

# CNN Model
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(img_size, img_size, 3)),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(train_gen.num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(train_gen, validation_data=val_gen, epochs=10)

import matplotlib.pyplot as plt

# Plot accuracy
plt.plot(history.history['accuracy'], label='train acc')
plt.plot(history.history['val_accuracy'], label='val acc')
plt.legend()
plt.title('CNN Accuracy')
plt.show()

import numpy as np
from tensorflow.keras.preprocessing import image

def predict_and_sort(image_path):
    img = image.load_img(image_path, target_size=(img_size, img_size))
    img_array = image.img_to_array(img)/255.
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    predicted_class = np.argmax(prediction)

    # Simulated robot arm command
    class_name = list(train_gen.class_indices.keys())[predicted_class]
    print(f"Detected: {class_name}")

    if class_name == "apple":
        print("Activating Arm: Sort to Bin A 🍎")
    elif class_name == "banana":
        print("Activating Arm: Sort to Bin B 🍌")
    else:
        print("Activating Arm: Sort to Bin C 🍊")

from tensorflow.keras.preprocessing.image import ImageDataGenerator

img_size = 100
batch_size = 32

datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_gen = datagen.flow_from_directory(
    '/content/drive/MyDrive/archive (9)',
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='categorical',
    subset='training'
)

val_gen = datagen.flow_from_directory(
    '/content/drive/MyDrive/archive (9)',
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation'
)

from tensorflow.keras import models, layers

cnn_model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(img_size, img_size, 3)),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(train_gen.num_classes, activation='softmax')
])

cnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
cnn_model.fit(train_gen, validation_data=val_gen, epochs=10)

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import Model

base_model = MobileNetV2(input_shape=(img_size, img_size, 3), include_top=False, weights='imagenet')
base_model.trainable = False  # Freeze base

model_mobilenet = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dense(train_gen.num_classes, activation='softmax')
])

model_mobilenet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_mobilenet.fit(train_gen, validation_data=val_gen, epochs=10)

import numpy as np
from tensorflow.keras.preprocessing import image

# ... (other imports and functions remain the same) ...

def extract_features(generator, num_samples):
    """Extract features from images using the generator."""
    features = []
    labels = []
    for i in range(num_samples // batch_size):
        x_batch, y_batch = next(generator)  # Use next(generator) instead of generator.next()
        flat = x_batch.reshape((x_batch.shape[0], -1))  # Flatten images
        features.append(flat)
        labels.append(np.argmax(y_batch, axis=1))
    return np.vstack(features), np.hstack(labels)

# ... (rest of the code remains the same) ...

X_train, y_train = extract_features(train_gen, train_gen.samples)
X_val, y_val = extract_features(val_gen, val_gen.samples)

# ... (continue with the rest of your code) ...

!pip install scikit-learn

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# ... (your previous code) ...

# Assuming X_train, y_train, X_val, y_val are defined from previous code
rf_classifier = RandomForestClassifier(random_state=42)  # Initialize Random Forest
rf_classifier.fit(X_train, y_train)  # Train Random Forest
rf_pred = rf_classifier.predict(X_val)  # Make predictions

print(f"Basic CNN Accuracy: {cnn_model.evaluate(val_gen)[1]:.2f}")
print(f"MobileNetV2 Accuracy: {model_mobilenet.evaluate(val_gen)[1]:.2f}")
print("Random Forest Accuracy:", accuracy_score(y_val, rf_pred))

# You'll also need to similarly define and train an SVM model for the next line
# ... (define and train SVM, make predictions: svm_pred)
# print("SVM Accuracy:", accuracy_score(y_val, svm_pred))

import numpy as np
from tensorflow.keras.preprocessing import image

# ... (other imports and functions remain the same) ...

def extract_features(generator, num_samples):
    """Extract features from images using the generator."""
    features = []
    labels = []
    for i in range(num_samples // batch_size):
        x_batch, y_batch = next(generator)
        flat = x_batch.reshape((x_batch.shape[0], -1))
        features.append(flat)
        # Ensure labels are correctly extracted, this is likely the issue
        labels.extend(np.argmax(y_batch, axis=1))  # Use extend instead of append
    return np.vstack(features), np.array(labels) # Convert labels to a NumPy array

# ... (rest of the code remains the same) ...

X_train, y_train = extract_features(train_gen, train_gen.samples)
X_val, y_val = extract_features(val_gen, val_gen.samples)

# ... (continue with the rest of your code) ...

import cv2
import numpy as np
import matplotlib.pyplot as plt

def extract_quality_features(image_path):
    image = cv2.imread(image_path)
    image = cv2.resize(image, (300, 300))
    blur = cv2.GaussianBlur(image, (5,5), 0)
    hsv = cv2.cvtColor(blur, cv2.COLOR_BGR2HSV)

    # Color check (Hue mean)
    hue_mean = np.mean(hsv[:, :, 0])

    # Size check (Contour area)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    _, thresh = cv2.threshold(gray, 40, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    area = max([cv2.contourArea(c) for c in contours]) if contours else 0

    # Shape check (Aspect ratio)
    x, y, w, h = cv2.boundingRect(contours[0]) if contours else (0,0,1,1)
    aspect_ratio = float(w)/h

    # Defect detection (Edge density)
    edges = cv2.Canny(gray, 100, 200)
    edge_density = np.sum(edges > 0) / (300 * 300)

    return {
        "Hue Mean": round(hue_mean, 2),
        "Area": round(area, 2),
        "Aspect Ratio": round(aspect_ratio, 2),
        "Edge Density": round(edge_density, 4)
    }

def grade_fruit(features):
    grade = "C"  # Default

    if 25 < features["Hue Mean"] < 40:
        color_score = 1
    else:
        color_score = 0

    if features["Area"] > 10000:
        size_score = 1
    else:
        size_score = 0

    if 0.8 < features["Aspect Ratio"] < 1.2:
        shape_score = 1
    else:
        shape_score = 0

    if features["Edge Density"] < 0.01:
        defect_score = 1
    else:
        defect_score = 0

    total_score = color_score + size_score + shape_score + defect_score

    if total_score == 4:
        grade = "A"
    elif total_score == 3:
        grade = "B"
    elif total_score == 2:
        grade = "C"
    else:
        grade = "Reject"

    return grade, total_score

dataset_path = '/content/drive/MyDrive/archive (9)/apple.jpg' # Update with an actual image path inside the directory
features = extract_quality_features(dataset_path)
grade, score = grade_fruit(features)

print("Quality Matrix:", features)
print("Grade:", grade)

Quality Matrix: {
    'Hue Mean': 33.2,
    'Area': 12654.8,
    'Aspect Ratio': 0.98,
    'Edge Density': 0.0083
}
Grade: A